server:
  port: 5048
  
spring:
  application:
    name: cibil-score-service
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka